### ISSUE TITLE
Unable to find grunt

### ISSUE THREAD

**Issue by havenchyk** [just-boris/build-proxy#1]
This line is not working for me. 
`require('child_process').execFile('grunt', [action], done);`

![image of error](http://i.imgur.com/lnhwBhw.png)

But I'm able to get grunt with `require('grunt')`

**Comment by havenchyk** [comment]
Sorry, my fault.

**Comment by just-boris** [comment]
I guess your `grunt` is unavailabe in your `$PATH`.
Maybe you should install [grunt-cli](https://www.npmjs.com/package/grunt-cli)?

**Comment by havenchyk** [comment]
@just-boris I just need to specify `--base` and `--gruntfile` params.
